In [1]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[                                 0.0000,
                                          0.0000,
               -654847608700481908254965760.0000],
        [                                 0.0000,
         -405710708045017320182827431493632.0000,
                                          0.0000],
        [                                 0.0000,
                                          0.0000,
                                          0.0000],
        [                                 0.0000,
         -453844602137521297376523904352256.0000,
                                          0.0000],
        [-439010366646764585542407698776064.0000,
                                          0.0000,
               -665030211429169580746997760.0000]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4482, 0.0196, 0.1131],
        [0.4095, 0.2553, 0.5499],
        [0.3263, 0.3233, 0.8145],
        [0.0429, 0.1034, 0.5939],
        [0.8096, 0.0853, 0.3248]])


In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float64)
print(x)
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.7981, -2.5819, -0.8203],
        [-0.8029, -0.2673,  2.6177],
        [-0.4584, -1.1823, -0.9143],
        [-0.1608, -0.3784, -0.8696],
        [-1.0211,  0.5049, -0.5876]], dtype=torch.float64)
torch.Size([5, 3])


In [15]:
y = torch.rand(5, 3, dtype=torch.double)
print(x + y)

print(torch.add(x, y))

result = torch.empty(5, 3, dtype=torch.double)
torch.add(x, y, out=result)
print(result)

y.add_(x) # y = x + y
print(y)

tensor([[-0.8412, -2.0673, -0.4851],
        [-0.0872,  0.5881,  2.7290],
        [-0.2551, -0.6726, -0.0702],
        [ 0.0932, -0.1297, -0.8299],
        [-0.0317,  1.5041,  0.2839]], dtype=torch.float64)
tensor([[-0.8412, -2.0673, -0.4851],
        [-0.0872,  0.5881,  2.7290],
        [-0.2551, -0.6726, -0.0702],
        [ 0.0932, -0.1297, -0.8299],
        [-0.0317,  1.5041,  0.2839]], dtype=torch.float64)
tensor([[-0.8412, -2.0673, -0.4851],
        [-0.0872,  0.5881,  2.7290],
        [-0.2551, -0.6726, -0.0702],
        [ 0.0932, -0.1297, -0.8299],
        [-0.0317,  1.5041,  0.2839]], dtype=torch.float64)
tensor([[-0.8412, -2.0673, -0.4851],
        [-0.0872,  0.5881,  2.7290],
        [-0.2551, -0.6726, -0.0702],
        [ 0.0932, -0.1297, -0.8299],
        [-0.0317,  1.5041,  0.2839]], dtype=torch.float64)


In [16]:
print(x[:, 1])

tensor([-2.5819, -0.2673, -1.1823, -0.3784,  0.5049], dtype=torch.float64)


In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # -1 可以进行自动推导维度
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1186])
0.11860071122646332


In [19]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [21]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu", torch.double))

tensor([1.1186], device='cuda:0')
tensor([1.1186], dtype=torch.float64)
